[package]
name = "flv-node-client"
version = "4.0.0"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
license = "Apache-2.0"
repository = "https://github.com/infinyon/fluvio"
description = "Node JS Client for Fluvio"
readme = "REAMD.md"

[lib]
crate-type = ["cdylib"]
test = false

[dependencies]
log = "0.4.8"
futures = { version = "0.3.4", features = ['async-await'] }
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
flv-future-aio = { version = "2.2.1" }
flv-api-sc = { version = "1.2.0"}
node-bindgen = { version = "2.1.1" }
kf-protocol = { version = "1.1.2" }
flv-util = { version = "0.2.0" }
flv-client = { version = "3.1.0" }

[build-dependencies]
node-bindgen = { version = "2.1.1", features = ["build"] }